# Lift Me Up Playground

## Transcript Download

In [ ]:
#from youtube_transcript_api import YouTubeTranscriptApi
#video_id = 'aXPhHuieFIE'
#test = YouTubeTranscriptApi.get_transcript(video_id)

## The main dataset 

In [1]:
import pandas as pd
from datasets import load_dataset

In [2]:
dataset = load_dataset("jkhedri/psychology-dataset")
df = pd.DataFrame(dataset)

In [3]:
df.head()

train
0  {'question': 'I'm feeling really anxious latel...
1  {'question': 'I think my partner may be cheati...
2  {'question': 'I'm feeling really overwhelmed w...
3  {'question': 'I'm having trouble sleeping and ...
4  {'question': 'I've been feeling really anxious...

### Getting Questions and Response_J into their own columns

In [4]:
df.train[0]

{'question': "I'm feeling really anxious lately and I don't know why.",
 'response_j': "It's common to feel anxious at times, and there can be many reasons for it. Have there been any recent changes or stressors in your life that may be contributing to your anxiety? Let's work together to identify any triggers and develop coping strategies to manage your anxiety.",
 'response_k': 'Anxiety is just a sign of weakness. You need to toughen up and stop worrying so much. Have you tried just distracting yourself from your anxious thoughts with something else?'}

In [5]:
questions = []
answers = []
for r in range(len(df)):
    questions.append(df.train[r]['question'])
    answers.append(df.train[r]['response_j'])

In [6]:
df['question'] = questions
df['answer'] = answers 

In [7]:
df.head()

train  \
0  {'question': 'I'm feeling really anxious latel...   
1  {'question': 'I think my partner may be cheati...   
2  {'question': 'I'm feeling really overwhelmed w...   
3  {'question': 'I'm having trouble sleeping and ...   
4  {'question': 'I've been feeling really anxious...   

                                            question  \
0  I'm feeling really anxious lately and I don't ...   
1  I think my partner may be cheating on me. What...   
2  I'm feeling really overwhelmed with work and s...   
3  I'm having trouble sleeping and I'm constantly...   
4  I've been feeling really anxious lately, and I...   

                                              answer  
0  It's common to feel anxious at times, and ther...  
1  It's understandable to feel worried and suspic...  
2  It sounds like you're going through a difficul...  
3  It's important to talk to your doctor about an...  
4  It's common to feel anxious without knowing th...

### Calling my X and my y

In [8]:
X_all = df['question']
y_all = df['answer']

In [9]:
new_df = df.drop(columns = 'train')
new_df.head()

question  \
0  I'm feeling really anxious lately and I don't ...   
1  I think my partner may be cheating on me. What...   
2  I'm feeling really overwhelmed with work and s...   
3  I'm having trouble sleeping and I'm constantly...   
4  I've been feeling really anxious lately, and I...   

                                              answer  
0  It's common to feel anxious at times, and ther...  
1  It's understandable to feel worried and suspic...  
2  It sounds like you're going through a difficul...  
3  It's important to talk to your doctor about an...  
4  It's common to feel anxious without knowing th...

In [10]:
from sklearn.model_selection import train_test_split
X, X_test, y, y_test = train_test_split( X_all, y_all, test_size=0.6, random_state=42)

In [11]:
X = pd.DataFrame(X)
X.head()

question
3583                 I'm struggling with my body image.
9673  My partner and I have been having communicatio...
7922  I'm feeling really stressed out. What can I do...
7444  I'm feeling really anxious lately and can't se...
6213  I'm having trouble with my body image. What sh...

### Trying to build manually?

In [12]:
#from tensorflow.keras.models import Sequential
#from tensorflow.keras import layers

# Model definition
#model = Sequential()
#model.add(layers.Dense(20, activation='relu', input_dim=713))
#model.add(layers.Dense(10, activation='relu'))
#model.add(layers.Dense(1, activation='softmax'))
#model.compile(
#    optimizer='adam',
#    loss='categorical_crossentropy', 
#    metrics = 'accuracy')

### Using pre-trained model 

pre-trained model selected : ayoubkirouane/BERT-Emotions-Classifier

#### testing with a recognised pre-trained model

In [13]:
from transformers import BertTokenizer, TFBertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained("bert-base-uncased")
text = "I'm struggling with my body image"
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)

2024-03-04 17:23:23.495055: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-04 17:23:23.533704: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-04 17:23:23.719009: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-04 17:23:23.719067: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-04 17:23:23.768312: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

In [14]:
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 10, 768), dtype=float32, numpy=
array([[[ 0.16655256,  0.30138662,  0.04182276, ..., -0.10977775,
          0.08999836,  0.15080006],
        [ 0.1134204 ,  0.49956554, -0.704957  , ...,  0.06546806,
          0.6343676 ,  0.36404106],
        [ 0.46951455, -0.08654222,  0.43994883, ..., -0.6057686 ,
          0.23529495, -0.20612116],
        ...,
        [ 0.41608667, -0.42830357,  0.31148222, ..., -0.830958  ,
         -0.02026437,  0.08181397],
        [ 0.23044956, -0.11350092, -0.38386637, ...,  0.306188  ,
          0.32906383, -0.01288066],
        [ 0.74707985,  0.28112668, -0.12774366, ...,  0.00091529,
         -0.47692922, -0.2707505 ]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-7.73431897e-01, -1.66651905e-01,  5.44427514e-01,
         4.36887681e-01, -3.74479860e-01, -1.02269962e-01,
         7.18245208e-01,  1.40059367e-01,  3.23325962e-

#### testing with the pre-trained model I found

In [15]:
from transformers import pipeline

# Load the BERT-Emotions-Classifier
classifier = pipeline("text-classification", model="ayoubkirouane/BERT-Emotions-Classifier")

# Input text
text = "Your input text here"

# Perform emotion classification
results = classifier(text)

# Display the classification results
print(results)


ValueError: Could not load model ayoubkirouane/BERT-Emotions-Classifier with any of the following classes: (<class 'transformers.models.auto.modeling_tf_auto.TFAutoModelForSequenceClassification'>, <class 'transformers.models.bert.modeling_tf_bert.TFBertForSequenceClassification'>). See the original errors:

while loading with TFAutoModelForSequenceClassification, an error is thrown:
Traceback (most recent call last):
  File "/home/tiphaineoz/.pyenv/versions/3.10.6/envs/Lift_Me_Up/lib/python3.10/site-packages/transformers/pipelines/base.py", line 279, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home/tiphaineoz/.pyenv/versions/3.10.6/envs/Lift_Me_Up/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/home/tiphaineoz/.pyenv/versions/3.10.6/envs/Lift_Me_Up/lib/python3.10/site-packages/transformers/modeling_tf_utils.py", line 2799, in from_pretrained
    raise EnvironmentError(
OSError: ayoubkirouane/BERT-Emotions-Classifier does not appear to have a file named tf_model.h5 but there is a file for PyTorch weights. Use `from_pt=True` to load this model from those weights.

while loading with TFBertForSequenceClassification, an error is thrown:
Traceback (most recent call last):
  File "/home/tiphaineoz/.pyenv/versions/3.10.6/envs/Lift_Me_Up/lib/python3.10/site-packages/transformers/pipelines/base.py", line 279, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home/tiphaineoz/.pyenv/versions/3.10.6/envs/Lift_Me_Up/lib/python3.10/site-packages/transformers/modeling_tf_utils.py", line 2799, in from_pretrained
    raise EnvironmentError(
OSError: ayoubkirouane/BERT-Emotions-Classifier does not appear to have a file named tf_model.h5 but there is a file for PyTorch weights. Use `from_pt=True` to load this model from those weights.




In [ ]:
from transformers import pipeline
model_name = "ayoubkirouane/BERT-Emotions-Classifier"

# Load the BERT-Emotions-Classifier
classifier = pipeline("text-classification", model=model_name, from_pt = True)

# Input text
text = "I'm struggling with my body image"

# Perform emotion classification
results = classifier(text)

# Display the classification results
print(results)


#### tokenizing with the model I found

In [ ]:
from transformers import AutoTokenizer, TFAutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained(model_name)

tokens = tokenizer.encode("I'm struggling with my body image", return_tensors = "tf")

print(tokens)

In [ ]:
model = TFAutoModelForSeq2SeqLM.from_pretrained(model_name, from_pt = True)

output_tokens = model.generate(tokens)

print(output_tokens)

print(tokenizer.decode(output[0]))

In [1]:
import tensorflow as tf

2024-03-14 12:35:37.751567: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-14 12:35:37.779094: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-14 12:35:37.779120: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-14 12:35:37.779797: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-14 12:35:37.784886: I tensorflow/core/platform/cpu_feature_guar

In [3]:
model = tf.keras.models.load_model('../model_registry/rnn_saved_model.h5')

In [4]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 160, 50)           27700     
                                                                 
 lstm_7 (LSTM)               (None, 64)                29440     
                                                                 
 dense_34 (Dense)            (None, 300)               19500     
                                                                 
 dense_35 (Dense)            (None, 200)               60200     
                                                                 
 dense_36 (Dense)            (None, 120)               24120     
                                                                 
 dense_37 (Dense)            (None, 120)               14520     
                                                                 
 dense_38 (Dense)            (None, 33)               